apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cache-server
    labels:
      app: cache-server
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: cache-server
    template:
      metadata:
        labels:
          app: cache-server
      spec:
        containers:
        - name: cache-server
          image: registry.access.redhat.com/jboss-datagrid-7/datagrid73-openshift:1.0
          env:
          - name: DEFAULT_CACHE_EXPIRATION_LIFESPAN
            value: "10000"
          - name: INFINISPAN_CONNECTORS
            value: hotrod
          ports:
          - containerPort: 8778
            protocol: TCP
          - containerPort: 11211
            protocol: TCP
          - containerPort: 11222
            protocol: TCP
          - containerPort: 11333
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 9990
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: cache-server
    labels:
      app: cache-server
  spec:
    type: ClusterIP
    selector:
      app: cache-server
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 11211-tcp
      port: 11211
      protocol: TCP
      targetPort: 11211
    - name: 11222-tcp
      port: 11222
      protocol: TCP
      targetPort: 11222
    - name: 11333-tcp
      port: 11333
      protocol: TCP
      targetPort: 11333
